# Setup
title: Just another tech blog
url: https://abousselmi.github.io
paginate: 1
baseurl: ""
#permalink: pretty
permalink: /:title

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-3YMNR9B7BX

# Specify the author for blog posts
author:
  name: abousselmi
  url: https://about.me/abousselmi

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Home
    url: /

  - title: Posts
    url: /archive

  - title: About
    url: /about
